version: "3.8"

services:
  restapi:
    build:
      context: ..
      dockerfile: ./build/package/Dockerfile
    container_name: rest-server
    hostname: rest-server
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - mynet
    environment:
      PORT: 8080
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - mynet
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: secret

networks:
  mynet:
    driver: bridge

volumes:
  postgres-data:
